name: Deploy to staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - id: deploy
        name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@main
        with:
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: false
          version: ${{ github.head_ref }}
          project_id: playground-jje

      - name: Post deployment URL
        uses: thollander/actions-comment-pull-request@master
        with:
          message: 🔗 https://${{ github.head_ref }}-dot-playground-jje.nw.r.appspot.com]
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}